[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
idle_battle = "EZhEi1iBCbUyT3tdiMGpye1GVqSzCcSPWeyYxEZ6drn2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest"